### ISSUE TITLE
Design support for the Janus community

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/book#10]
## Goals
Provide design support for Janus community

## What's needed

1. High fidelity mockups for the Janus community site janus-idp.io
2. Branded image to be used as bumpers for any of our Janus branded You Tube videos
3. Janus branded GSlide template
4. Ideate on Janus swag ideas, for use at conferences

## Issues in epic

- https://github.com/janus-idp/book/issues/6
- https://github.com/janus-idp/book/issues/7
- https://github.com/janus-idp/book/issues/8
- https://github.com/janus-idp/book/issues/9

**Comment by jasperchui** [comment]
Issues completed.
