### ISSUE TITLE
Hi-fi mocks for janus-idp.io

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/book#6]
## Goals
High fidelity mockups for the Janus community site janus-idp.io based on requirements and ideas found [here](https://docs.google.com/document/d/1DOMbB7fp-Locl-JbSEU_YJc2imGKB54yOylwMGiMnlE/edit#heading=h.jn7l4ezi1fu7)

**Comment by lstewart74** [comment]
@serenamarie125 
Who is owner of current iteration of janus-idp.io?
