### ISSUE TITLE
Branded imagery to be used as bumpers for Janus branded videos

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/book#7]
## Goals
Branded imagery to be used as bumpers for any of our Janus branded You Tube videos

**Comment by lstewart74** [comment]
@serenamarie125 
Can you provide examples of "branded bumpers"? Not familiar with that term.

**Comment by serenamarie125** [comment]
![Screenshot 2023-02-21 at 9 45 54 AM](https://user-images.githubusercontent.com/12504403/220376744-a3ad277d-6131-4703-b6a5-af0bae9baddd.png)

**Comment by serenamarie125** [comment]
![Screenshot 2023-02-21 at 9 48 24 AM](https://user-images.githubusercontent.com/12504403/220377426-b143d8a5-2c6b-4d5b-99cb-b6bba15b82a4.png)

**Comment by lstewart74** [comment]
What image format is required for this? A regular jpg or png?

**Comment by serenamarie125** [comment]
here are some examples of what they do for developers.redhat.com
![Screenshot 2023-02-21 at 9 49 53 AM](https://user-images.githubusercontent.com/12504403/220377815-7130395d-2e8c-4732-96ef-1928d1916324.png)

**Comment by serenamarie125** [comment]
I think Figma is probably best - then we could edit there and generate a PNG.  wdyt?

**Comment by serenamarie125** [comment]
sorry for all the screenshots :) this is from YouTube ... alternatively people may choose to edit the actual recording and add
![Screenshot 2023-02-21 at 9 51 54 AM](https://user-images.githubusercontent.com/12504403/220378363-7f71655c-9e2b-4eef-8729-c4c852615f5e.png)
