### ISSUE TITLE
Janus branded GSlide template

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/book#8]
## Goals
Provide a Janus branded GSlide template

## Why is this needed
This will help strengthen the Janus brand

**Comment by lstewart74** [comment]
@serenamarie125 

Dark theme or light theme? or both?

Colors...use cyan as the primary?

**Comment by serenamarie125** [comment]
@lstewart74 
Yes, let's use cyan as the primary.
Eventually both, but I'd suggest light theme first
