### ISSUE TITLE
Janus swag ideas

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/book#9]
## Goal
Ideate on swag ideas, for use at conferences.

Starting with Red Hat Summit & OpenShift Commons, we would like to have Janus branded swag.

## Why is this needed
This will help strengthen the Janus brand

## Notes
Do we need a tagline? mascot ?

**Comment by lstewart74** [comment]
@serenamarie125 
Is there a team or dept. that can be tasked to order swag or is this on us?
What items are you interested in?

- [ ] shirts
- [ ] hoodies
- [ ] stickers
- [ ] keychains
- [ ] coasters
- [ ] other (please provide examples)

Regarding tagline/mascot...should we put out a call to the community for suggestions?

**Comment by schwesig** [comment]
![IMG_3372](https://user-images.githubusercontent.com/89909507/230111069-516a8626-d6e8-48f1-9520-a7339dba6987.jpg)
![IMG_3371](https://user-images.githubusercontent.com/89909507/230111075-3487a474-0d67-4b6f-8a8f-3d4ce2432ba7.jpg)
![IMG_3370](https://user-images.githubusercontent.com/89909507/230111078-b7a43f3c-f0ba-4f80-88c1-0bb046da512c.jpg)
![IMG_3369](https://user-images.githubusercontent.com/89909507/230111088-020f3334-731d-4148-9799-8e350c200371.jpg)

**Comment by serenamarie125** [comment]
FYI - our branding assets can be found here: https://drive.google.com/drive/folders/1hJRsGXnbH6CuBvIYakwu2hnk9gdeOUva 
 @schwesig could you update to be aligned?  Thanks!

**Comment by schwesig** [comment]
@serenamarie125 are these files somewhere in the repo or only in google drive?
The color is off on the pictures (bad light), but follows the website logo colors.
Is the website logo/color/spacing different than in the google folder?

Can you please point out, what is not aligned?
Is it the font? The logo file in the google drive has two different fonts (round ending corners and flat ending corners).
or the color?
or the logo itself? Website has flat ending corners and the logo file round ones.
